global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aws-node'
    static_configs:
      - targets: ['${AWS_INSTANCE_IP}:9100']
    metrics_path: '/metrics'

  - job_name: 'ibm-node'
    static_configs:
      - targets: ['${IBM_INSTANCE_IP}:9100']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
